        ;Autor Piero Torpoco Llacza
	list	p=16f877A       ;Indica el tipo de procesador a programar
        INCLUDE	"p16f877a.inc"  ;Incluye en el programa el fichero de definiciones del uC seleccionado
        __CONFIG _CP_OFF& _DEBUG_OFF& _WRT_OFF& _CPD_OFF& _LVP_OFF& _BODEN_OFF& _PWRTE_ON& _WDT_OFF& _XT_OSC    ; selecciona el estado de los bits de configuración

	;Definicion de variables	
HELP2	EQU	0x21
TEMPQ	EQU	0x22
TIEMPO1	EQU	0x23
TIEMPO2	EQU	0x24
CUENTA	EQU	0x25
FIRST	EQU	0x26
TEMP	EQU	0x27
MARCA	EQU	0x28
HELP	EQU	0x29
	
	ORG     0x00        ; Se define el origen del programa
	GOTO	INICIO
	
	ORG	0x04
	GOTO	INT
	
        ;************CONFIGURACIÓN DE PUERTOS*********
INICIO  BSF     STATUS,RP0  ; Selección banco 1
        CLRF	TRISC       ; Configuración del puerto C como salida
        CLRF    TRISD       ; Configuración del puerto D como salida
	CLRF	TRISB
	COMF	TRISB
	;Configurando la interrupción RBO/INT
        MOVLW	B'01000000' ; Configurando flanco de subida
        MOVWF	OPTION_REG  ;
	MOVLW	B'10010000' ; Habilitamos GIE e INTE
        MOVWF	INTCON
        BCF     STATUS,RP0  ; Seleccionando el banco 0
	
        ;************INICIO PROGRAMA PRINCIPAL*********
        BCF	INTCON,1
	CLRF	TEMP
	CLRF    PORTD      
	CLRF	PORTC
	CALL	CLR
	
PRIN	CLRF	CUENTA
	MOVLW	B'10000000'
	MOVWF	PORTC
	MOVF	FIRST,W
	MOVWF	FSR
	MOVLW	0x3F
	MOVWF	MARCA
PRIN1	MOVF	INDF,W
	MOVWF	HELP
	MOVF	FSR,W
	MOVWF	HELP2	
	MOVF	MARCA,W
	MOVWF	FSR
	MOVF	INDF,W
	ANDWF	HELP,W
	MOVWF	PORTD
	MOVF	HELP2,W
	MOVWF	FSR
	CALL	DELAY
	INCF	FSR,F
	INCF	MARCA,F
	BCF	STATUS,C
	RRF	PORTC
	INCF	CUENTA
	MOVLW	.8
	SUBWF	CUENTA,W
	BTFSS	STATUS,Z
	GOTO	PRIN1
	GOTO	PRIN
	
REP	BTFSC	TEMP,0
	CALL	ESCRIB
	BTFSC	TEMP,1
	CALL	CLR
	BTFSC	TEMP,2
	CALL	IZQ
	BTFSC	TEMP,3
	CALL	SUBIR
	BTFSC	TEMP,4
	CALL	BAJAR
	BTFSC	TEMP,5
	CALL	ERASE
	BTFSC	TEMP,6
	CALL	DER
	RETURN	

CLR     CALL	APAGAR
	MOVLW	0x37
	MOVWF	FIRST
	CLRF	CUENTA
	MOVLW	0x30
	MOVWF	FSR
AGAIN	MOVLW	B'11111111'
	MOVWF	INDF
	INCF	FSR,F
	INCF	CUENTA
	MOVLW	.23
	SUBWF	CUENTA,W
	BTFSS	STATUS,Z
	GOTO	AGAIN
	CLRF	CUENTA
	MOVLW	0x37
	MOVWF	FSR
	MOVLW	B'11111110'
	MOVWF   INDF
	RETURN
	
DER	MOVLW	0x30
	SUBWF	FIRST,W
	BTFSS	STATUS,Z
	DECF	FIRST
	RETURN
	
ESCRIB	CLRF	CUENTA
	MOVLW	0x3F
	MOVWF	MARCA
	MOVF	FIRST,W
	MOVWF	FSR
ESCRIB1	MOVF	INDF,W
	MOVWF	HELP
	MOVF	FSR,W
	MOVWF	HELP2
	MOVF	MARCA,W
	MOVWF	FSR
	MOVF	HELP,W
	ANDWF	INDF,F
	MOVF	HELP2,W
	MOVWF	FSR
	INCF	FSR
	INCF	MARCA
	INCF	CUENTA
	MOVLW	.8
	SUBWF	CUENTA,W
	BTFSS	STATUS,Z
	GOTO	ESCRIB1
	RETURN
	
ERASE	CLRF	CUENTA
	MOVLW	0x3F
	MOVWF	MARCA
	MOVF	FIRST,W
	MOVWF	FSR
ERASE1	MOVF	INDF,W
	MOVWF	HELP
	MOVF	FSR,W
	MOVWF	HELP2
	MOVF	MARCA,W
	MOVWF	FSR
	COMF	HELP,W
	IORWF	INDF,F
	MOVF	HELP2,W
	MOVWF	FSR
	INCF	FSR
	INCF	MARCA
	INCF	CUENTA
	MOVLW	.8
	SUBWF	CUENTA,W
	BTFSS	STATUS,Z
	GOTO	ERASE1
	RETURN
	
IZQ	MOVLW	0x37
	SUBWF	FIRST,W
	BTFSS	STATUS,Z
	INCF	FIRST
	RETURN
	
SUBIR	MOVLW	0x37
	MOVWF	FSR
	BSF	STATUS,C
	BTFSC	INDF,0
	RRF	INDF
	RETURN
	
BAJAR	MOVLW	0x37
	MOVWF	FSR
	BSF	STATUS,C
	BTFSC	INDF,7
	RLF	INDF
	RETURN

	;**************INTERRUPCION*******************
INT     MOVWF	TEMPQ
	SWAPF   PORTB,W
        ANDLW   B'00001111'
        CALL    TABLA1
        MOVWF   TEMP
	CALL	REP
	MOVF	TEMPQ,W
	BCF	INTCON,1
	RETFIE
	
	;*****************TABLA1************************
TABLA1   ADDWF   PCL, F
	RETLW	0x00
	RETLW	0x00
	RETLW	0x00
        RETLW   0x01
	RETLW	0x00
	RETLW	0x00
	RETLW	0x00
	RETLW	0x02
	RETLW	0x00
	RETLW	0x00
	RETLW	0x00
        RETLW   0x04        
        RETLW   0x08        
        RETLW   0x10        
        RETLW   0x20        
        RETLW   0x40
	
	
        ;************APAGAR DISPLAY********************
APAGAR  MOVLW   0xFF        ; Cargamos el dato FF a W
        MOVWF   PORTD       ; Pone 1?s a todos los bits del puerto D
        RETURN
        
        ;*****************DELAY************************
DELAY   MOVLW   0x08        ; Configuramos el tiempo del retardo
        MOVWF   TIEMPO1
DELAY1  MOVWF   TIEMPO2
DELAY2  NOP
        NOP
        NOP
        NOP
        DECFSZ  TIEMPO2,F
        GOTO    DELAY2
        DECFSZ  TIEMPO1,F
        GOTO    DELAY1
        RETURN
	
	
        END